name: Deploy site to Pages

on:
  push:
    branches:
      - master
  # Allows manual triggers from the Actions tab
  workflow_dispatch:

# Sets permissions to allow the GITHUB_TOKEN to write pages content and get an OIDC token
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Use v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify -s kyudo --baseURL "${{ steps.pages.outputs.base_url }}/kyudo"

      - name: Prepare deploy directory
        run: |
          mkdir public
          mkdir public/kyudo
          cp -r kyudo/public/* public/kyudo/
          # Copy all files from repo root except .git, kyudo/public, and deploy itself
          shopt -s extglob
          cp -r !(kyudo|public|.git|.github) public/
      - name: List public directory tree
        run: |
          echo "public directory files:"
          tree public || find public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public