name: Deploy site to Pages

on:
  push:
    branches:
      - master
  # Allows manual triggers from the Actions tab
  workflow_dispatch:

# Sets permissions to allow the GITHUB_TOKEN to write pages content and get an OIDC token
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Use v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify -s kyudo --baseURL "${{ steps.pages.outputs.base_url }}/kyudo"

      - name: Prepare deploy directory
        run: |
          mkdir public
          mkdir public/kyudo
          cp -r kyudo/public/* public/kyudo/
          # Copy all files from repo root except .git, kyudo/public, and deploy itself
          shopt -s extglob
          cp -r !(kyudo|public|.git|.github) public/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # The deploy-pages action uses the artifact from the 'build' job
        uses: actions/deploy-pages@v4 # Use v4